// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'DCF Cleaner';

  @override
  String get homeTitle => 'Home';

  @override
  String get chooseFolder => 'Choose folder';

  @override
  String get reselectFolder => 'Re-select';

  @override
  String get selectedFolderLabel => 'Selected folder:';

  @override
  String currentDirectoryTitle(String path) {
    return 'Current root: $path';
  }

  @override
  String get chooseFolderNotSupported =>
      'Folder picker is not supported on this platform.';

  @override
  String get chooseFolderCanceled => 'Canceled.';

  @override
  String get chooseFolderFailed => 'Failed to open folder picker.';

  @override
  String get chooseFolderTimedOut => 'Folder picker timed out.';

  @override
  String get detailTitle => 'Details';

  @override
  String get detailLoadFailed => 'Failed to load file details.';

  @override
  String get detailName => 'Name';

  @override
  String get detailPath => 'Path';

  @override
  String get detailType => 'Type';

  @override
  String get detailSize => 'Size on disk';

  @override
  String get detailFolderSizeCalculated => 'Folder size (calculated)';

  @override
  String get detailModified => 'Modified';

  @override
  String get detailAccessed => 'Accessed';

  @override
  String get detailChanged => 'Changed';

  @override
  String get detailTypeFile => 'File';

  @override
  String get detailTypeDirectory => 'Folder';

  @override
  String get detailTypeLink => 'Link';

  @override
  String get detailTypeOther => 'Other';

  @override
  String get aiSuggestButton => 'AI Suggest';

  @override
  String get aiSuggestLoading => 'Generating...';

  @override
  String get aiSuggestFailedTitle => 'AI suggestion failed';

  @override
  String get aiSuggestErrorConfigIncomplete =>
      'AI configuration is incomplete.';

  @override
  String get aiSuggestErrorBadUrl => 'Base URL is invalid.';

  @override
  String get aiSuggestErrorTimeout => 'Request timed out.';

  @override
  String get aiSuggestErrorConnectFailed => 'Connection failed.';

  @override
  String get aiSuggestErrorHttpUnknown => 'Request failed (HTTP error).';

  @override
  String aiSuggestErrorHttp(int code) {
    return 'Request failed (HTTP $code).';
  }

  @override
  String get aiSuggestErrorInternal =>
      'Request failed due to an internal error.';

  @override
  String get aiSuggestErrorUnknown => 'Request failed.';

  @override
  String get aiSuggestSystemPrompt =>
      'You are an expert in file cleanup. Analyze the provided file/folder information, focusing on whether deletion is recommended and what serious consequences deletion may cause.\n\nOutput requirements:\n- Plain text only (no Markdown, no bold, no bullet points).\n- You must strictly use the following 3 tags (tags must be output verbatim, in order), and write content after each tag:\n[[DCF_SUMMARY]]\n(one short summary)\n[[DCF_ADVICE]]\n(one short deletion advice)\n[[DCF_END]]\n- Output ONLY the tags and their contents. Output nothing else.\n- Within 200 words.';

  @override
  String get aiSuggestUnknown => 'Unknown';

  @override
  String aiSuggestUserPromptFile(String path, String name, String sizeText,
      int sizeBytes, String modified, String accessed, String changed) {
    return 'File info:\nPath: $path\nName: $name\nTotal size (allocated on disk): $sizeText (${sizeBytes}B)\nModified: $modified\nAccessed: $accessed\nChanged: $changed';
  }

  @override
  String aiSuggestUserPromptFolder(
      String path,
      String name,
      String sizeText,
      int sizeBytes,
      String modified,
      String accessed,
      String changed,
      String top10) {
    return 'Folder info:\nPath: $path\nName: $name\nTotal size (allocated on disk): $sizeText (${sizeBytes}B)\nModified: $modified\nAccessed: $accessed\nChanged: $changed\n\nTop 10 largest direct children (non-recursive):\n$top10\n\nNote: If a child name starts with \"*\", it may be a hard-link duplicate; disk usage may have already been counted elsewhere.';
  }

  @override
  String get aiSuggestParsedSummaryLabel => 'Summary';

  @override
  String get aiSuggestParsedAdviceLabel => 'Advice';

  @override
  String get aiSuggestDisclaimer =>
      'This suggestion is generated by AI and is not affiliated with this app. You are solely responsible. Please proceed with caution.';

  @override
  String get aiSuggestTop10Empty => '- (empty)';

  @override
  String get aiConfigTitle => 'AI Settings';

  @override
  String get aiConfigBaseUrlLabel => 'Base URL';

  @override
  String get aiConfigBaseUrlHint => 'e.g. https://api.openai.com/v1';

  @override
  String get aiConfigModelLabel => 'Model';

  @override
  String get aiConfigModelHint => 'e.g. gpt-4o-mini';

  @override
  String get aiConfigApiKeyLabel => 'API Key';

  @override
  String get aiConfigValidating => 'Validating...';

  @override
  String get aiConfigValidateFailedTitle => 'Validation failed';

  @override
  String get aiConfigSuccessTitle => 'Configured successfully!';

  @override
  String get aiConfigErrorIncomplete => 'Configuration is incomplete.';

  @override
  String get aiConfigErrorBadUrl => 'Base URL is invalid.';

  @override
  String get aiConfigErrorTimeout => 'Request timed out.';

  @override
  String get aiConfigErrorConnectFailed => 'Connection failed.';

  @override
  String get aiConfigErrorHttpUnknown => 'Request failed (HTTP error).';

  @override
  String aiConfigErrorHttp(int code) {
    return 'Request failed (HTTP $code).';
  }

  @override
  String get aiConfigErrorInternal =>
      'Validation failed due to an internal error.';

  @override
  String get aiConfigErrorUnknown => 'Validation failed.';

  @override
  String get menuOpenInFileManager => 'Open in File Manager';

  @override
  String get menuDelete => 'Delete';

  @override
  String get menuPermanentDelete => 'Permanently delete';

  @override
  String get commonOk => 'OK';

  @override
  String get commonCancel => 'Cancel';

  @override
  String get commonConfirm => 'Confirm';

  @override
  String get deleteFailed => 'Delete failed.';

  @override
  String get permanentDeleteFailed => 'Permanent delete failed.';

  @override
  String get binNameMac => 'Trash';

  @override
  String get binNameWindows => 'Recycle Bin';

  @override
  String get deleteConfirmTitle => 'Delete?';

  @override
  String deleteToBinConfirmPrimaryFile(String name, String bin) {
    return 'This will move \"$name\" to $bin.';
  }

  @override
  String deleteToBinConfirmPrimaryFolder(String name, String bin) {
    return 'This will move the folder \"$name\" to $bin.';
  }

  @override
  String deleteToBinConfirmUndo(String bin) {
    return 'You can undo this from $bin.';
  }

  @override
  String deleteToBinConfirmReleaseSpace(String bin) {
    return 'Only after you empty $bin will the storage space be fully freed.';
  }

  @override
  String get permanentDeleteConfirmTitle => 'Permanently delete?';

  @override
  String permanentDeleteConfirmMessageFile(String name) {
    return 'This will permanently delete \"$name\".';
  }

  @override
  String permanentDeleteConfirmMessageFolder(String name) {
    return 'This will permanently delete the folder \"$name\" and all of its contents.';
  }

  @override
  String get permanentDeleteIrreversibleWarning =>
      'This action cannot be undone!';

  @override
  String get counterPrompt => 'You have pushed the button this many times:';

  @override
  String get incrementTooltip => 'Increment';
}
